### ISSUE TITLE
Add Hex Code value in a Div which has a Id of 'hexCode'

### ISSUE THREAD

**Issue by aayushyadavz** [AayushYadavz/Unlimited_Colors#1]
I just want you to add some more functionality in this project by simply doing a task in which you have to add every color Hex Code in that Div which has a Id of hexCode, so that on every color change it displays the hex code of each and every color but removes the previous one which is gone. Hope you got my point and will fix my issue. Thank You and contact me on 'ayushyadav24nov1234@gmail.com'

**Comment by StarKnightt** [comment]
Fixed the issue
